/*
 * This file is generated by jOOQ.
 */
package net.haaim.web.jooq.entity.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import net.haaim.web.jooq.entity.JHaaimDb;
import net.haaim.web.jooq.entity.Keys;
import net.haaim.web.jooq.entity.tables.records.JExamItemRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 문제출제
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JExamItem extends TableImpl<JExamItemRecord> {

    private static final long serialVersionUID = 95661647;

    /**
     * The reference instance of <code>haaim_db.exam_item</code>
     */
    public static final JExamItem EXAM_ITEM = new JExamItem();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JExamItemRecord> getRecordType() {
        return JExamItemRecord.class;
    }

    /**
     * The column <code>haaim_db.exam_item.exam_no</code>.
     */
    public final TableField<JExamItemRecord, Integer> EXAM_NO = createField(DSL.name("exam_no"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>haaim_db.exam_item.no</code>. 문제순서
     */
    public final TableField<JExamItemRecord, Integer> NO = createField(DSL.name("no"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "문제순서");

    /**
     * The column <code>haaim_db.exam_item.item_no</code>.
     */
    public final TableField<JExamItemRecord, Integer> ITEM_NO = createField(DSL.name("item_no"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>haaim_db.exam_item.input_id</code>.
     */
    public final TableField<JExamItemRecord, String> INPUT_ID = createField(DSL.name("input_id"), org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>haaim_db.exam_item.input_date</code>.
     */
    public final TableField<JExamItemRecord, LocalDateTime> INPUT_DATE = createField(DSL.name("input_date"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>haaim_db.exam_item.update_id</code>.
     */
    public final TableField<JExamItemRecord, String> UPDATE_ID = createField(DSL.name("update_id"), org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>haaim_db.exam_item.update_date</code>.
     */
    public final TableField<JExamItemRecord, LocalDateTime> UPDATE_DATE = createField(DSL.name("update_date"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * Create a <code>haaim_db.exam_item</code> table reference
     */
    public JExamItem() {
        this(DSL.name("exam_item"), null);
    }

    /**
     * Create an aliased <code>haaim_db.exam_item</code> table reference
     */
    public JExamItem(String alias) {
        this(DSL.name(alias), EXAM_ITEM);
    }

    /**
     * Create an aliased <code>haaim_db.exam_item</code> table reference
     */
    public JExamItem(Name alias) {
        this(alias, EXAM_ITEM);
    }

    private JExamItem(Name alias, Table<JExamItemRecord> aliased) {
        this(alias, aliased, null);
    }

    private JExamItem(Name alias, Table<JExamItemRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("문제출제"), TableOptions.table());
    }

    public <O extends Record> JExamItem(Table<O> child, ForeignKey<O, JExamItemRecord> key) {
        super(child, key, EXAM_ITEM);
    }

    @Override
    public Schema getSchema() {
        return JHaaimDb.HAAIM_DB;
    }

    @Override
    public UniqueKey<JExamItemRecord> getPrimaryKey() {
        return Keys.KEY_EXAM_ITEM_PRIMARY;
    }

    @Override
    public List<UniqueKey<JExamItemRecord>> getKeys() {
        return Arrays.<UniqueKey<JExamItemRecord>>asList(Keys.KEY_EXAM_ITEM_PRIMARY);
    }

    @Override
    public JExamItem as(String alias) {
        return new JExamItem(DSL.name(alias), this);
    }

    @Override
    public JExamItem as(Name alias) {
        return new JExamItem(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JExamItem rename(String name) {
        return new JExamItem(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JExamItem rename(Name name) {
        return new JExamItem(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, Integer, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
