/*
 * This file is generated by jOOQ.
 */
package net.haaim.web.jooq.entity.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import net.haaim.web.jooq.entity.JHaaimDb;
import net.haaim.web.jooq.entity.Keys;
import net.haaim.web.jooq.entity.tables.records.JGroupCodeRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 코드 그룹
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JGroupCode extends TableImpl<JGroupCodeRecord> {

    private static final long serialVersionUID = -1130373011;

    /**
     * The reference instance of <code>haaim_db.group_code</code>
     */
    public static final JGroupCode GROUP_CODE = new JGroupCode();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JGroupCodeRecord> getRecordType() {
        return JGroupCodeRecord.class;
    }

    /**
     * The column <code>haaim_db.group_code.no</code>.
     */
    public final TableField<JGroupCodeRecord, Integer> NO = createField(DSL.name("no"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>haaim_db.group_code.code</code>. 코드
     */
    public final TableField<JGroupCodeRecord, String> CODE = createField(DSL.name("code"), org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false), this, "코드");

    /**
     * The column <code>haaim_db.group_code.code_name</code>. 코드명
     */
    public final TableField<JGroupCodeRecord, String> CODE_NAME = createField(DSL.name("code_name"), org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "코드명");

    /**
     * The column <code>haaim_db.group_code.use_yn</code>. 사용여부
     */
    public final TableField<JGroupCodeRecord, Integer> USE_YN = createField(DSL.name("use_yn"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "사용여부");

    /**
     * The column <code>haaim_db.group_code.input_id</code>.
     */
    public final TableField<JGroupCodeRecord, String> INPUT_ID = createField(DSL.name("input_id"), org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>haaim_db.group_code.input_date</code>.
     */
    public final TableField<JGroupCodeRecord, LocalDateTime> INPUT_DATE = createField(DSL.name("input_date"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>haaim_db.group_code.update_id</code>.
     */
    public final TableField<JGroupCodeRecord, String> UPDATE_ID = createField(DSL.name("update_id"), org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>haaim_db.group_code.update_date</code>.
     */
    public final TableField<JGroupCodeRecord, LocalDateTime> UPDATE_DATE = createField(DSL.name("update_date"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * Create a <code>haaim_db.group_code</code> table reference
     */
    public JGroupCode() {
        this(DSL.name("group_code"), null);
    }

    /**
     * Create an aliased <code>haaim_db.group_code</code> table reference
     */
    public JGroupCode(String alias) {
        this(DSL.name(alias), GROUP_CODE);
    }

    /**
     * Create an aliased <code>haaim_db.group_code</code> table reference
     */
    public JGroupCode(Name alias) {
        this(alias, GROUP_CODE);
    }

    private JGroupCode(Name alias, Table<JGroupCodeRecord> aliased) {
        this(alias, aliased, null);
    }

    private JGroupCode(Name alias, Table<JGroupCodeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("코드 그룹"), TableOptions.table());
    }

    public <O extends Record> JGroupCode(Table<O> child, ForeignKey<O, JGroupCodeRecord> key) {
        super(child, key, GROUP_CODE);
    }

    @Override
    public Schema getSchema() {
        return JHaaimDb.HAAIM_DB;
    }

    @Override
    public Identity<JGroupCodeRecord, Integer> getIdentity() {
        return Keys.IDENTITY_GROUP_CODE;
    }

    @Override
    public UniqueKey<JGroupCodeRecord> getPrimaryKey() {
        return Keys.KEY_GROUP_CODE_PRIMARY;
    }

    @Override
    public List<UniqueKey<JGroupCodeRecord>> getKeys() {
        return Arrays.<UniqueKey<JGroupCodeRecord>>asList(Keys.KEY_GROUP_CODE_PRIMARY);
    }

    @Override
    public JGroupCode as(String alias) {
        return new JGroupCode(DSL.name(alias), this);
    }

    @Override
    public JGroupCode as(Name alias) {
        return new JGroupCode(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JGroupCode rename(String name) {
        return new JGroupCode(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JGroupCode rename(Name name) {
        return new JGroupCode(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, Integer, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
