/*
 * This file is generated by jOOQ.
 */
package net.haaim.web.jooq.entity;


import net.haaim.web.jooq.entity.tables.JAuthority;
import net.haaim.web.jooq.entity.tables.JClass;
import net.haaim.web.jooq.entity.tables.JClassCurriculum;
import net.haaim.web.jooq.entity.tables.JClassStudent;
import net.haaim.web.jooq.entity.tables.JCode;
import net.haaim.web.jooq.entity.tables.JCurriculum;
import net.haaim.web.jooq.entity.tables.JExamItem;
import net.haaim.web.jooq.entity.tables.JExamList;
import net.haaim.web.jooq.entity.tables.JExamUser;
import net.haaim.web.jooq.entity.tables.JGroupCode;
import net.haaim.web.jooq.entity.tables.JItemPool;
import net.haaim.web.jooq.entity.tables.JMenu;
import net.haaim.web.jooq.entity.tables.JMonthlyReport;
import net.haaim.web.jooq.entity.tables.JNotice;
import net.haaim.web.jooq.entity.tables.JScoreMngt;
import net.haaim.web.jooq.entity.tables.JStudentInfo;
import net.haaim.web.jooq.entity.tables.JUser;


/**
 * Convenience access to all tables in haaim_db
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 메뉴권한관리
     */
    public static final JAuthority AUTHORITY = JAuthority.AUTHORITY;

    /**
     * 수업관리
     */
    public static final JClass CLASS = JClass.CLASS;

    /**
     * 클래스&amp;커리큘럼 매핑
     */
    public static final JClassCurriculum CLASS_CURRICULUM = JClassCurriculum.CLASS_CURRICULUM;

    /**
     * 클래스&amp;학생 매핑정보
     */
    public static final JClassStudent CLASS_STUDENT = JClassStudent.CLASS_STUDENT;

    /**
     * 코드
     */
    public static final JCode CODE = JCode.CODE;

    /**
     * 커리큘럼
     */
    public static final JCurriculum CURRICULUM = JCurriculum.CURRICULUM;

    /**
     * 문제출제
     */
    public static final JExamItem EXAM_ITEM = JExamItem.EXAM_ITEM;

    /**
     * 문제출제목록
     */
    public static final JExamList EXAM_LIST = JExamList.EXAM_LIST;

    /**
     * 시험대상 목록
     */
    public static final JExamUser EXAM_USER = JExamUser.EXAM_USER;

    /**
     * 코드 그룹
     */
    public static final JGroupCode GROUP_CODE = JGroupCode.GROUP_CODE;

    /**
     * 문제은행
     */
    public static final JItemPool ITEM_POOL = JItemPool.ITEM_POOL;

    /**
     * 메뉴
     */
    public static final JMenu MENU = JMenu.MENU;

    /**
     * 월간리포트
     */
    public static final JMonthlyReport MONTHLY_REPORT = JMonthlyReport.MONTHLY_REPORT;

    /**
     * 공지사항
     */
    public static final JNotice NOTICE = JNotice.NOTICE;

    /**
     * 시험점수관리(중간/기말/모의고사/수능점수)
     */
    public static final JScoreMngt SCORE_MNGT = JScoreMngt.SCORE_MNGT;

    /**
     * 학생정보
     */
    public static final JStudentInfo STUDENT_INFO = JStudentInfo.STUDENT_INFO;

    /**
     * 사용자
     */
    public static final JUser USER = JUser.USER;
}
