/*
 * This file is generated by jOOQ.
 */
package net.haaim.web.jooq.entity.tables.records;


import java.time.LocalDateTime;

import net.haaim.web.jooq.entity.tables.JAuthority;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 메뉴권한관리
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JAuthorityRecord extends UpdatableRecordImpl<JAuthorityRecord> implements Record7<String, Integer, Integer, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = -1091855793;

    /**
     * Setter for <code>haaim_db.authority.menu_code</code>. 메뉴코드
     */
    public void setMenuCode(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>haaim_db.authority.menu_code</code>. 메뉴코드
     */
    public String getMenuCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>haaim_db.authority.user_type</code>. 사용자권한
     */
    public void setUserType(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>haaim_db.authority.user_type</code>. 사용자권한
     */
    public Integer getUserType() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>haaim_db.authority.use_yn</code>.
     */
    public void setUseYn(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>haaim_db.authority.use_yn</code>.
     */
    public Integer getUseYn() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>haaim_db.authority.input_id</code>.
     */
    public void setInputId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>haaim_db.authority.input_id</code>.
     */
    public String getInputId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>haaim_db.authority.input_date</code>.
     */
    public void setInputDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>haaim_db.authority.input_date</code>.
     */
    public LocalDateTime getInputDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>haaim_db.authority.update_id</code>.
     */
    public void setUpdateId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>haaim_db.authority.update_id</code>.
     */
    public String getUpdateId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>haaim_db.authority.update_date</code>.
     */
    public void setUpdateDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>haaim_db.authority.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, Integer, Integer, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, Integer, Integer, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JAuthority.AUTHORITY.MENU_CODE;
    }

    @Override
    public Field<Integer> field2() {
        return JAuthority.AUTHORITY.USER_TYPE;
    }

    @Override
    public Field<Integer> field3() {
        return JAuthority.AUTHORITY.USE_YN;
    }

    @Override
    public Field<String> field4() {
        return JAuthority.AUTHORITY.INPUT_ID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return JAuthority.AUTHORITY.INPUT_DATE;
    }

    @Override
    public Field<String> field6() {
        return JAuthority.AUTHORITY.UPDATE_ID;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return JAuthority.AUTHORITY.UPDATE_DATE;
    }

    @Override
    public String component1() {
        return getMenuCode();
    }

    @Override
    public Integer component2() {
        return getUserType();
    }

    @Override
    public Integer component3() {
        return getUseYn();
    }

    @Override
    public String component4() {
        return getInputId();
    }

    @Override
    public LocalDateTime component5() {
        return getInputDate();
    }

    @Override
    public String component6() {
        return getUpdateId();
    }

    @Override
    public LocalDateTime component7() {
        return getUpdateDate();
    }

    @Override
    public String value1() {
        return getMenuCode();
    }

    @Override
    public Integer value2() {
        return getUserType();
    }

    @Override
    public Integer value3() {
        return getUseYn();
    }

    @Override
    public String value4() {
        return getInputId();
    }

    @Override
    public LocalDateTime value5() {
        return getInputDate();
    }

    @Override
    public String value6() {
        return getUpdateId();
    }

    @Override
    public LocalDateTime value7() {
        return getUpdateDate();
    }

    @Override
    public JAuthorityRecord value1(String value) {
        setMenuCode(value);
        return this;
    }

    @Override
    public JAuthorityRecord value2(Integer value) {
        setUserType(value);
        return this;
    }

    @Override
    public JAuthorityRecord value3(Integer value) {
        setUseYn(value);
        return this;
    }

    @Override
    public JAuthorityRecord value4(String value) {
        setInputId(value);
        return this;
    }

    @Override
    public JAuthorityRecord value5(LocalDateTime value) {
        setInputDate(value);
        return this;
    }

    @Override
    public JAuthorityRecord value6(String value) {
        setUpdateId(value);
        return this;
    }

    @Override
    public JAuthorityRecord value7(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    @Override
    public JAuthorityRecord values(String value1, Integer value2, Integer value3, String value4, LocalDateTime value5, String value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JAuthorityRecord
     */
    public JAuthorityRecord() {
        super(JAuthority.AUTHORITY);
    }

    /**
     * Create a detached, initialised JAuthorityRecord
     */
    public JAuthorityRecord(String menuCode, Integer userType, Integer useYn, String inputId, LocalDateTime inputDate, String updateId, LocalDateTime updateDate) {
        super(JAuthority.AUTHORITY);

        set(0, menuCode);
        set(1, userType);
        set(2, useYn);
        set(3, inputId);
        set(4, inputDate);
        set(5, updateId);
        set(6, updateDate);
    }
}
