/*
 * This file is generated by jOOQ.
 */
package net.haaim.web.jooq.entity.tables.records;


import java.time.LocalDateTime;

import net.haaim.web.jooq.entity.tables.JClassCurriculum;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 클래스&amp;커리큘럼 매핑
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JClassCurriculumRecord extends UpdatableRecordImpl<JClassCurriculumRecord> implements Record7<Integer, Integer, Integer, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = -853866777;

    /**
     * Setter for <code>haaim_db.class_curriculum.no</code>.
     */
    public void setNo(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>haaim_db.class_curriculum.no</code>.
     */
    public Integer getNo() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>haaim_db.class_curriculum.class_no</code>. 클래스번호
     */
    public void setClassNo(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>haaim_db.class_curriculum.class_no</code>. 클래스번호
     */
    public Integer getClassNo() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>haaim_db.class_curriculum.cur_id</code>. 컬리큘럼ID
     */
    public void setCurId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>haaim_db.class_curriculum.cur_id</code>. 컬리큘럼ID
     */
    public Integer getCurId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>haaim_db.class_curriculum.input_id</code>.
     */
    public void setInputId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>haaim_db.class_curriculum.input_id</code>.
     */
    public String getInputId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>haaim_db.class_curriculum.input_date</code>.
     */
    public void setInputDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>haaim_db.class_curriculum.input_date</code>.
     */
    public LocalDateTime getInputDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>haaim_db.class_curriculum.update_id</code>.
     */
    public void setUpdateId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>haaim_db.class_curriculum.update_id</code>.
     */
    public String getUpdateId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>haaim_db.class_curriculum.update_date</code>.
     */
    public void setUpdateDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>haaim_db.class_curriculum.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, Integer, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Integer, Integer, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return JClassCurriculum.CLASS_CURRICULUM.NO;
    }

    @Override
    public Field<Integer> field2() {
        return JClassCurriculum.CLASS_CURRICULUM.CLASS_NO;
    }

    @Override
    public Field<Integer> field3() {
        return JClassCurriculum.CLASS_CURRICULUM.CUR_ID;
    }

    @Override
    public Field<String> field4() {
        return JClassCurriculum.CLASS_CURRICULUM.INPUT_ID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return JClassCurriculum.CLASS_CURRICULUM.INPUT_DATE;
    }

    @Override
    public Field<String> field6() {
        return JClassCurriculum.CLASS_CURRICULUM.UPDATE_ID;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return JClassCurriculum.CLASS_CURRICULUM.UPDATE_DATE;
    }

    @Override
    public Integer component1() {
        return getNo();
    }

    @Override
    public Integer component2() {
        return getClassNo();
    }

    @Override
    public Integer component3() {
        return getCurId();
    }

    @Override
    public String component4() {
        return getInputId();
    }

    @Override
    public LocalDateTime component5() {
        return getInputDate();
    }

    @Override
    public String component6() {
        return getUpdateId();
    }

    @Override
    public LocalDateTime component7() {
        return getUpdateDate();
    }

    @Override
    public Integer value1() {
        return getNo();
    }

    @Override
    public Integer value2() {
        return getClassNo();
    }

    @Override
    public Integer value3() {
        return getCurId();
    }

    @Override
    public String value4() {
        return getInputId();
    }

    @Override
    public LocalDateTime value5() {
        return getInputDate();
    }

    @Override
    public String value6() {
        return getUpdateId();
    }

    @Override
    public LocalDateTime value7() {
        return getUpdateDate();
    }

    @Override
    public JClassCurriculumRecord value1(Integer value) {
        setNo(value);
        return this;
    }

    @Override
    public JClassCurriculumRecord value2(Integer value) {
        setClassNo(value);
        return this;
    }

    @Override
    public JClassCurriculumRecord value3(Integer value) {
        setCurId(value);
        return this;
    }

    @Override
    public JClassCurriculumRecord value4(String value) {
        setInputId(value);
        return this;
    }

    @Override
    public JClassCurriculumRecord value5(LocalDateTime value) {
        setInputDate(value);
        return this;
    }

    @Override
    public JClassCurriculumRecord value6(String value) {
        setUpdateId(value);
        return this;
    }

    @Override
    public JClassCurriculumRecord value7(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    @Override
    public JClassCurriculumRecord values(Integer value1, Integer value2, Integer value3, String value4, LocalDateTime value5, String value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JClassCurriculumRecord
     */
    public JClassCurriculumRecord() {
        super(JClassCurriculum.CLASS_CURRICULUM);
    }

    /**
     * Create a detached, initialised JClassCurriculumRecord
     */
    public JClassCurriculumRecord(Integer no, Integer classNo, Integer curId, String inputId, LocalDateTime inputDate, String updateId, LocalDateTime updateDate) {
        super(JClassCurriculum.CLASS_CURRICULUM);

        set(0, no);
        set(1, classNo);
        set(2, curId);
        set(3, inputId);
        set(4, inputDate);
        set(5, updateId);
        set(6, updateDate);
    }
}
