/*
 * This file is generated by jOOQ.
 */
package net.haaim.web.jooq.entity.tables.records;


import java.time.LocalDateTime;

import net.haaim.web.jooq.entity.tables.JClass;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 수업관리
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JClassRecord extends UpdatableRecordImpl<JClassRecord> implements Record14<Integer, Integer, String, Integer, String, String, String, String, Integer, String, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = -1527701987;

    /**
     * Setter for <code>haaim_db.class.class_no</code>. 클래스 번호
     */
    public void setClassNo(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>haaim_db.class.class_no</code>. 클래스 번호
     */
    public Integer getClassNo() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>haaim_db.class.year</code>. 기간
     */
    public void setYear(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>haaim_db.class.year</code>. 기간
     */
    public Integer getYear() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>haaim_db.class.class_name</code>. 클래스명
     */
    public void setClassName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>haaim_db.class.class_name</code>. 클래스명
     */
    public String getClassName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>haaim_db.class.teacher_no</code>. 교사 no.
     */
    public void setTeacherNo(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>haaim_db.class.teacher_no</code>. 교사 no.
     */
    public Integer getTeacherNo() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>haaim_db.class.start_date</code>.
     */
    public void setStartDate(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>haaim_db.class.start_date</code>.
     */
    public String getStartDate() {
        return (String) get(4);
    }

    /**
     * Setter for <code>haaim_db.class.end_date</code>.
     */
    public void setEndDate(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>haaim_db.class.end_date</code>.
     */
    public String getEndDate() {
        return (String) get(5);
    }

    /**
     * Setter for <code>haaim_db.class.day_time</code>. 수업 요일 &amp; 시간 
     */
    public void setDayTime(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>haaim_db.class.day_time</code>. 수업 요일 &amp; 시간 
     */
    public String getDayTime() {
        return (String) get(6);
    }

    /**
     * Setter for <code>haaim_db.class.textbook</code>. 교재
     */
    public void setTextbook(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>haaim_db.class.textbook</code>. 교재
     */
    public String getTextbook() {
        return (String) get(7);
    }

    /**
     * Setter for <code>haaim_db.class.pass_score</code>. PASS 기준 점수
     */
    public void setPassScore(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>haaim_db.class.pass_score</code>. PASS 기준 점수
     */
    public Integer getPassScore() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>haaim_db.class.description</code>. 기타정보
     */
    public void setDescription(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>haaim_db.class.description</code>. 기타정보
     */
    public String getDescription() {
        return (String) get(9);
    }

    /**
     * Setter for <code>haaim_db.class.input_id</code>.
     */
    public void setInputId(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>haaim_db.class.input_id</code>.
     */
    public String getInputId() {
        return (String) get(10);
    }

    /**
     * Setter for <code>haaim_db.class.input_date</code>.
     */
    public void setInputDate(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>haaim_db.class.input_date</code>.
     */
    public LocalDateTime getInputDate() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>haaim_db.class.update_id</code>.
     */
    public void setUpdateId(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>haaim_db.class.update_id</code>.
     */
    public String getUpdateId() {
        return (String) get(12);
    }

    /**
     * Setter for <code>haaim_db.class.update_date</code>.
     */
    public void setUpdateDate(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>haaim_db.class.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Integer, Integer, String, Integer, String, String, String, String, Integer, String, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Integer, Integer, String, Integer, String, String, String, String, Integer, String, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return JClass.CLASS.CLASS_NO;
    }

    @Override
    public Field<Integer> field2() {
        return JClass.CLASS.YEAR;
    }

    @Override
    public Field<String> field3() {
        return JClass.CLASS.CLASS_NAME;
    }

    @Override
    public Field<Integer> field4() {
        return JClass.CLASS.TEACHER_NO;
    }

    @Override
    public Field<String> field5() {
        return JClass.CLASS.START_DATE;
    }

    @Override
    public Field<String> field6() {
        return JClass.CLASS.END_DATE;
    }

    @Override
    public Field<String> field7() {
        return JClass.CLASS.DAY_TIME;
    }

    @Override
    public Field<String> field8() {
        return JClass.CLASS.TEXTBOOK;
    }

    @Override
    public Field<Integer> field9() {
        return JClass.CLASS.PASS_SCORE;
    }

    @Override
    public Field<String> field10() {
        return JClass.CLASS.DESCRIPTION;
    }

    @Override
    public Field<String> field11() {
        return JClass.CLASS.INPUT_ID;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return JClass.CLASS.INPUT_DATE;
    }

    @Override
    public Field<String> field13() {
        return JClass.CLASS.UPDATE_ID;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return JClass.CLASS.UPDATE_DATE;
    }

    @Override
    public Integer component1() {
        return getClassNo();
    }

    @Override
    public Integer component2() {
        return getYear();
    }

    @Override
    public String component3() {
        return getClassName();
    }

    @Override
    public Integer component4() {
        return getTeacherNo();
    }

    @Override
    public String component5() {
        return getStartDate();
    }

    @Override
    public String component6() {
        return getEndDate();
    }

    @Override
    public String component7() {
        return getDayTime();
    }

    @Override
    public String component8() {
        return getTextbook();
    }

    @Override
    public Integer component9() {
        return getPassScore();
    }

    @Override
    public String component10() {
        return getDescription();
    }

    @Override
    public String component11() {
        return getInputId();
    }

    @Override
    public LocalDateTime component12() {
        return getInputDate();
    }

    @Override
    public String component13() {
        return getUpdateId();
    }

    @Override
    public LocalDateTime component14() {
        return getUpdateDate();
    }

    @Override
    public Integer value1() {
        return getClassNo();
    }

    @Override
    public Integer value2() {
        return getYear();
    }

    @Override
    public String value3() {
        return getClassName();
    }

    @Override
    public Integer value4() {
        return getTeacherNo();
    }

    @Override
    public String value5() {
        return getStartDate();
    }

    @Override
    public String value6() {
        return getEndDate();
    }

    @Override
    public String value7() {
        return getDayTime();
    }

    @Override
    public String value8() {
        return getTextbook();
    }

    @Override
    public Integer value9() {
        return getPassScore();
    }

    @Override
    public String value10() {
        return getDescription();
    }

    @Override
    public String value11() {
        return getInputId();
    }

    @Override
    public LocalDateTime value12() {
        return getInputDate();
    }

    @Override
    public String value13() {
        return getUpdateId();
    }

    @Override
    public LocalDateTime value14() {
        return getUpdateDate();
    }

    @Override
    public JClassRecord value1(Integer value) {
        setClassNo(value);
        return this;
    }

    @Override
    public JClassRecord value2(Integer value) {
        setYear(value);
        return this;
    }

    @Override
    public JClassRecord value3(String value) {
        setClassName(value);
        return this;
    }

    @Override
    public JClassRecord value4(Integer value) {
        setTeacherNo(value);
        return this;
    }

    @Override
    public JClassRecord value5(String value) {
        setStartDate(value);
        return this;
    }

    @Override
    public JClassRecord value6(String value) {
        setEndDate(value);
        return this;
    }

    @Override
    public JClassRecord value7(String value) {
        setDayTime(value);
        return this;
    }

    @Override
    public JClassRecord value8(String value) {
        setTextbook(value);
        return this;
    }

    @Override
    public JClassRecord value9(Integer value) {
        setPassScore(value);
        return this;
    }

    @Override
    public JClassRecord value10(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public JClassRecord value11(String value) {
        setInputId(value);
        return this;
    }

    @Override
    public JClassRecord value12(LocalDateTime value) {
        setInputDate(value);
        return this;
    }

    @Override
    public JClassRecord value13(String value) {
        setUpdateId(value);
        return this;
    }

    @Override
    public JClassRecord value14(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    @Override
    public JClassRecord values(Integer value1, Integer value2, String value3, Integer value4, String value5, String value6, String value7, String value8, Integer value9, String value10, String value11, LocalDateTime value12, String value13, LocalDateTime value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JClassRecord
     */
    public JClassRecord() {
        super(JClass.CLASS);
    }

    /**
     * Create a detached, initialised JClassRecord
     */
    public JClassRecord(Integer classNo, Integer year, String className, Integer teacherNo, String startDate, String endDate, String dayTime, String textbook, Integer passScore, String description, String inputId, LocalDateTime inputDate, String updateId, LocalDateTime updateDate) {
        super(JClass.CLASS);

        set(0, classNo);
        set(1, year);
        set(2, className);
        set(3, teacherNo);
        set(4, startDate);
        set(5, endDate);
        set(6, dayTime);
        set(7, textbook);
        set(8, passScore);
        set(9, description);
        set(10, inputId);
        set(11, inputDate);
        set(12, updateId);
        set(13, updateDate);
    }
}
