/*
 * This file is generated by jOOQ.
 */
package net.haaim.web.jooq.entity.tables.records;


import java.time.LocalDateTime;

import net.haaim.web.jooq.entity.tables.JClassMngt;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 출석/테스트/과제/ 학업상태 레포트
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JClassMngtRecord extends UpdatableRecordImpl<JClassMngtRecord> implements Record9<Integer, String, Integer, String, String, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = -1439277042;

    /**
     * Setter for <code>haaim_db.class_mngt.student_no</code>.
     */
    public void setStudentNo(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>haaim_db.class_mngt.student_no</code>.
     */
    public Integer getStudentNo() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>haaim_db.class_mngt.date</code>.
     */
    public void setDate(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>haaim_db.class_mngt.date</code>.
     */
    public String getDate() {
        return (String) get(1);
    }

    /**
     * Setter for <code>haaim_db.class_mngt.attendance</code>. 출석
     */
    public void setAttendance(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>haaim_db.class_mngt.attendance</code>. 출석
     */
    public Integer getAttendance() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>haaim_db.class_mngt.homework</code>. 과제
     */
    public void setHomework(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>haaim_db.class_mngt.homework</code>. 과제
     */
    public String getHomework() {
        return (String) get(3);
    }

    /**
     * Setter for <code>haaim_db.class_mngt.comment</code>. 교사의견
     */
    public void setComment(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>haaim_db.class_mngt.comment</code>. 교사의견
     */
    public String getComment() {
        return (String) get(4);
    }

    /**
     * Setter for <code>haaim_db.class_mngt.input_id</code>.
     */
    public void setInputId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>haaim_db.class_mngt.input_id</code>.
     */
    public String getInputId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>haaim_db.class_mngt.input_date</code>.
     */
    public void setInputDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>haaim_db.class_mngt.input_date</code>.
     */
    public LocalDateTime getInputDate() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>haaim_db.class_mngt.update_id</code>.
     */
    public void setUpdateId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>haaim_db.class_mngt.update_id</code>.
     */
    public String getUpdateId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>haaim_db.class_mngt.update_date</code>.
     */
    public void setUpdateDate(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>haaim_db.class_mngt.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, String, Integer, String, String, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, String, Integer, String, String, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return JClassMngt.CLASS_MNGT.STUDENT_NO;
    }

    @Override
    public Field<String> field2() {
        return JClassMngt.CLASS_MNGT.DATE;
    }

    @Override
    public Field<Integer> field3() {
        return JClassMngt.CLASS_MNGT.ATTENDANCE;
    }

    @Override
    public Field<String> field4() {
        return JClassMngt.CLASS_MNGT.HOMEWORK;
    }

    @Override
    public Field<String> field5() {
        return JClassMngt.CLASS_MNGT.COMMENT;
    }

    @Override
    public Field<String> field6() {
        return JClassMngt.CLASS_MNGT.INPUT_ID;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return JClassMngt.CLASS_MNGT.INPUT_DATE;
    }

    @Override
    public Field<String> field8() {
        return JClassMngt.CLASS_MNGT.UPDATE_ID;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return JClassMngt.CLASS_MNGT.UPDATE_DATE;
    }

    @Override
    public Integer component1() {
        return getStudentNo();
    }

    @Override
    public String component2() {
        return getDate();
    }

    @Override
    public Integer component3() {
        return getAttendance();
    }

    @Override
    public String component4() {
        return getHomework();
    }

    @Override
    public String component5() {
        return getComment();
    }

    @Override
    public String component6() {
        return getInputId();
    }

    @Override
    public LocalDateTime component7() {
        return getInputDate();
    }

    @Override
    public String component8() {
        return getUpdateId();
    }

    @Override
    public LocalDateTime component9() {
        return getUpdateDate();
    }

    @Override
    public Integer value1() {
        return getStudentNo();
    }

    @Override
    public String value2() {
        return getDate();
    }

    @Override
    public Integer value3() {
        return getAttendance();
    }

    @Override
    public String value4() {
        return getHomework();
    }

    @Override
    public String value5() {
        return getComment();
    }

    @Override
    public String value6() {
        return getInputId();
    }

    @Override
    public LocalDateTime value7() {
        return getInputDate();
    }

    @Override
    public String value8() {
        return getUpdateId();
    }

    @Override
    public LocalDateTime value9() {
        return getUpdateDate();
    }

    @Override
    public JClassMngtRecord value1(Integer value) {
        setStudentNo(value);
        return this;
    }

    @Override
    public JClassMngtRecord value2(String value) {
        setDate(value);
        return this;
    }

    @Override
    public JClassMngtRecord value3(Integer value) {
        setAttendance(value);
        return this;
    }

    @Override
    public JClassMngtRecord value4(String value) {
        setHomework(value);
        return this;
    }

    @Override
    public JClassMngtRecord value5(String value) {
        setComment(value);
        return this;
    }

    @Override
    public JClassMngtRecord value6(String value) {
        setInputId(value);
        return this;
    }

    @Override
    public JClassMngtRecord value7(LocalDateTime value) {
        setInputDate(value);
        return this;
    }

    @Override
    public JClassMngtRecord value8(String value) {
        setUpdateId(value);
        return this;
    }

    @Override
    public JClassMngtRecord value9(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    @Override
    public JClassMngtRecord values(Integer value1, String value2, Integer value3, String value4, String value5, String value6, LocalDateTime value7, String value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JClassMngtRecord
     */
    public JClassMngtRecord() {
        super(JClassMngt.CLASS_MNGT);
    }

    /**
     * Create a detached, initialised JClassMngtRecord
     */
    public JClassMngtRecord(Integer studentNo, String date, Integer attendance, String homework, String comment, String inputId, LocalDateTime inputDate, String updateId, LocalDateTime updateDate) {
        super(JClassMngt.CLASS_MNGT);

        set(0, studentNo);
        set(1, date);
        set(2, attendance);
        set(3, homework);
        set(4, comment);
        set(5, inputId);
        set(6, inputDate);
        set(7, updateId);
        set(8, updateDate);
    }
}
