/*
 * This file is generated by jOOQ.
 */
package net.haaim.web.jooq.entity.tables.records;


import java.time.LocalDateTime;

import net.haaim.web.jooq.entity.tables.JClassStudent;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 클래스&amp;학생 매핑정보
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JClassStudentRecord extends UpdatableRecordImpl<JClassStudentRecord> implements Record8<Integer, Integer, Integer, Integer, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = 959275451;

    /**
     * Setter for <code>haaim_db.class_student.no</code>.
     */
    public void setNo(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>haaim_db.class_student.no</code>.
     */
    public Integer getNo() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>haaim_db.class_student.class_no</code>.
     */
    public void setClassNo(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>haaim_db.class_student.class_no</code>.
     */
    public Integer getClassNo() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>haaim_db.class_student.student_no</code>.
     */
    public void setStudentNo(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>haaim_db.class_student.student_no</code>.
     */
    public Integer getStudentNo() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>haaim_db.class_student.status</code>. drop 여부
     */
    public void setStatus(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>haaim_db.class_student.status</code>. drop 여부
     */
    public Integer getStatus() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>haaim_db.class_student.input_id</code>.
     */
    public void setInputId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>haaim_db.class_student.input_id</code>.
     */
    public String getInputId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>haaim_db.class_student.input_date</code>.
     */
    public void setInputDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>haaim_db.class_student.input_date</code>.
     */
    public LocalDateTime getInputDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>haaim_db.class_student.update_id</code>.
     */
    public void setUpdateId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>haaim_db.class_student.update_id</code>.
     */
    public String getUpdateId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>haaim_db.class_student.update_date</code>.
     */
    public void setUpdateDate(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>haaim_db.class_student.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Integer, Integer, Integer, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, Integer, Integer, Integer, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return JClassStudent.CLASS_STUDENT.NO;
    }

    @Override
    public Field<Integer> field2() {
        return JClassStudent.CLASS_STUDENT.CLASS_NO;
    }

    @Override
    public Field<Integer> field3() {
        return JClassStudent.CLASS_STUDENT.STUDENT_NO;
    }

    @Override
    public Field<Integer> field4() {
        return JClassStudent.CLASS_STUDENT.STATUS;
    }

    @Override
    public Field<String> field5() {
        return JClassStudent.CLASS_STUDENT.INPUT_ID;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return JClassStudent.CLASS_STUDENT.INPUT_DATE;
    }

    @Override
    public Field<String> field7() {
        return JClassStudent.CLASS_STUDENT.UPDATE_ID;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return JClassStudent.CLASS_STUDENT.UPDATE_DATE;
    }

    @Override
    public Integer component1() {
        return getNo();
    }

    @Override
    public Integer component2() {
        return getClassNo();
    }

    @Override
    public Integer component3() {
        return getStudentNo();
    }

    @Override
    public Integer component4() {
        return getStatus();
    }

    @Override
    public String component5() {
        return getInputId();
    }

    @Override
    public LocalDateTime component6() {
        return getInputDate();
    }

    @Override
    public String component7() {
        return getUpdateId();
    }

    @Override
    public LocalDateTime component8() {
        return getUpdateDate();
    }

    @Override
    public Integer value1() {
        return getNo();
    }

    @Override
    public Integer value2() {
        return getClassNo();
    }

    @Override
    public Integer value3() {
        return getStudentNo();
    }

    @Override
    public Integer value4() {
        return getStatus();
    }

    @Override
    public String value5() {
        return getInputId();
    }

    @Override
    public LocalDateTime value6() {
        return getInputDate();
    }

    @Override
    public String value7() {
        return getUpdateId();
    }

    @Override
    public LocalDateTime value8() {
        return getUpdateDate();
    }

    @Override
    public JClassStudentRecord value1(Integer value) {
        setNo(value);
        return this;
    }

    @Override
    public JClassStudentRecord value2(Integer value) {
        setClassNo(value);
        return this;
    }

    @Override
    public JClassStudentRecord value3(Integer value) {
        setStudentNo(value);
        return this;
    }

    @Override
    public JClassStudentRecord value4(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public JClassStudentRecord value5(String value) {
        setInputId(value);
        return this;
    }

    @Override
    public JClassStudentRecord value6(LocalDateTime value) {
        setInputDate(value);
        return this;
    }

    @Override
    public JClassStudentRecord value7(String value) {
        setUpdateId(value);
        return this;
    }

    @Override
    public JClassStudentRecord value8(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    @Override
    public JClassStudentRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5, LocalDateTime value6, String value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JClassStudentRecord
     */
    public JClassStudentRecord() {
        super(JClassStudent.CLASS_STUDENT);
    }

    /**
     * Create a detached, initialised JClassStudentRecord
     */
    public JClassStudentRecord(Integer no, Integer classNo, Integer studentNo, Integer status, String inputId, LocalDateTime inputDate, String updateId, LocalDateTime updateDate) {
        super(JClassStudent.CLASS_STUDENT);

        set(0, no);
        set(1, classNo);
        set(2, studentNo);
        set(3, status);
        set(4, inputId);
        set(5, inputDate);
        set(6, updateId);
        set(7, updateDate);
    }
}
