/*
 * This file is generated by jOOQ.
 */
package net.haaim.web.jooq.entity.tables.records;


import java.time.LocalDateTime;

import net.haaim.web.jooq.entity.tables.JCode;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 코드
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JCodeRecord extends UpdatableRecordImpl<JCodeRecord> implements Record9<Integer, String, String, String, Integer, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = -766504180;

    /**
     * Setter for <code>haaim_db.code.no</code>.
     */
    public void setNo(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>haaim_db.code.no</code>.
     */
    public Integer getNo() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>haaim_db.code.group_code</code>. 그룹코드
     */
    public void setGroupCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>haaim_db.code.group_code</code>. 그룹코드
     */
    public String getGroupCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>haaim_db.code.code</code>. 코드
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>haaim_db.code.code</code>. 코드
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>haaim_db.code.code_name</code>. 코드명
     */
    public void setCodeName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>haaim_db.code.code_name</code>. 코드명
     */
    public String getCodeName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>haaim_db.code.use_yn</code>. 사용여부
     */
    public void setUseYn(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>haaim_db.code.use_yn</code>. 사용여부
     */
    public Integer getUseYn() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>haaim_db.code.input_id</code>.
     */
    public void setInputId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>haaim_db.code.input_id</code>.
     */
    public String getInputId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>haaim_db.code.input_date</code>.
     */
    public void setInputDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>haaim_db.code.input_date</code>.
     */
    public LocalDateTime getInputDate() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>haaim_db.code.update_id</code>.
     */
    public void setUpdateId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>haaim_db.code.update_id</code>.
     */
    public String getUpdateId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>haaim_db.code.update_date</code>.
     */
    public void setUpdateDate(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>haaim_db.code.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, String, String, String, Integer, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, String, String, String, Integer, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return JCode.CODE.NO;
    }

    @Override
    public Field<String> field2() {
        return JCode.CODE.GROUP_CODE;
    }

    @Override
    public Field<String> field3() {
        return JCode.CODE.CODE_;
    }

    @Override
    public Field<String> field4() {
        return JCode.CODE.CODE_NAME;
    }

    @Override
    public Field<Integer> field5() {
        return JCode.CODE.USE_YN;
    }

    @Override
    public Field<String> field6() {
        return JCode.CODE.INPUT_ID;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return JCode.CODE.INPUT_DATE;
    }

    @Override
    public Field<String> field8() {
        return JCode.CODE.UPDATE_ID;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return JCode.CODE.UPDATE_DATE;
    }

    @Override
    public Integer component1() {
        return getNo();
    }

    @Override
    public String component2() {
        return getGroupCode();
    }

    @Override
    public String component3() {
        return getCode();
    }

    @Override
    public String component4() {
        return getCodeName();
    }

    @Override
    public Integer component5() {
        return getUseYn();
    }

    @Override
    public String component6() {
        return getInputId();
    }

    @Override
    public LocalDateTime component7() {
        return getInputDate();
    }

    @Override
    public String component8() {
        return getUpdateId();
    }

    @Override
    public LocalDateTime component9() {
        return getUpdateDate();
    }

    @Override
    public Integer value1() {
        return getNo();
    }

    @Override
    public String value2() {
        return getGroupCode();
    }

    @Override
    public String value3() {
        return getCode();
    }

    @Override
    public String value4() {
        return getCodeName();
    }

    @Override
    public Integer value5() {
        return getUseYn();
    }

    @Override
    public String value6() {
        return getInputId();
    }

    @Override
    public LocalDateTime value7() {
        return getInputDate();
    }

    @Override
    public String value8() {
        return getUpdateId();
    }

    @Override
    public LocalDateTime value9() {
        return getUpdateDate();
    }

    @Override
    public JCodeRecord value1(Integer value) {
        setNo(value);
        return this;
    }

    @Override
    public JCodeRecord value2(String value) {
        setGroupCode(value);
        return this;
    }

    @Override
    public JCodeRecord value3(String value) {
        setCode(value);
        return this;
    }

    @Override
    public JCodeRecord value4(String value) {
        setCodeName(value);
        return this;
    }

    @Override
    public JCodeRecord value5(Integer value) {
        setUseYn(value);
        return this;
    }

    @Override
    public JCodeRecord value6(String value) {
        setInputId(value);
        return this;
    }

    @Override
    public JCodeRecord value7(LocalDateTime value) {
        setInputDate(value);
        return this;
    }

    @Override
    public JCodeRecord value8(String value) {
        setUpdateId(value);
        return this;
    }

    @Override
    public JCodeRecord value9(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    @Override
    public JCodeRecord values(Integer value1, String value2, String value3, String value4, Integer value5, String value6, LocalDateTime value7, String value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JCodeRecord
     */
    public JCodeRecord() {
        super(JCode.CODE);
    }

    /**
     * Create a detached, initialised JCodeRecord
     */
    public JCodeRecord(Integer no, String groupCode, String code, String codeName, Integer useYn, String inputId, LocalDateTime inputDate, String updateId, LocalDateTime updateDate) {
        super(JCode.CODE);

        set(0, no);
        set(1, groupCode);
        set(2, code);
        set(3, codeName);
        set(4, useYn);
        set(5, inputId);
        set(6, inputDate);
        set(7, updateId);
        set(8, updateDate);
    }
}
