/*
 * This file is generated by jOOQ.
 */
package net.haaim.web.jooq.entity.tables.records;


import java.time.LocalDateTime;

import net.haaim.web.jooq.entity.tables.JCurriculum;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 커리큘럼
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JCurriculumRecord extends UpdatableRecordImpl<JCurriculumRecord> implements Record10<Integer, Integer, Integer, Integer, String, String, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = -1974983359;

    /**
     * Setter for <code>haaim_db.curriculum.no</code>.
     */
    public void setNo(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>haaim_db.curriculum.no</code>.
     */
    public Integer getNo() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>haaim_db.curriculum.year</code>.
     */
    public void setYear(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>haaim_db.curriculum.year</code>.
     */
    public Integer getYear() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>haaim_db.curriculum.grade</code>. 학년
     */
    public void setGrade(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>haaim_db.curriculum.grade</code>. 학년
     */
    public Integer getGrade() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>haaim_db.curriculum.course</code>. 학기/과정
     */
    public void setCourse(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>haaim_db.curriculum.course</code>. 학기/과정
     */
    public Integer getCourse() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>haaim_db.curriculum.large_category</code>. 대분류
     */
    public void setLargeCategory(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>haaim_db.curriculum.large_category</code>. 대분류
     */
    public String getLargeCategory() {
        return (String) get(4);
    }

    /**
     * Setter for <code>haaim_db.curriculum.medium_category</code>. 중분류
     */
    public void setMediumCategory(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>haaim_db.curriculum.medium_category</code>. 중분류
     */
    public String getMediumCategory() {
        return (String) get(5);
    }

    /**
     * Setter for <code>haaim_db.curriculum.input_id</code>.
     */
    public void setInputId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>haaim_db.curriculum.input_id</code>.
     */
    public String getInputId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>haaim_db.curriculum.input_date</code>.
     */
    public void setInputDate(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>haaim_db.curriculum.input_date</code>.
     */
    public LocalDateTime getInputDate() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>haaim_db.curriculum.update_id</code>.
     */
    public void setUpdateId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>haaim_db.curriculum.update_id</code>.
     */
    public String getUpdateId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>haaim_db.curriculum.update_date</code>.
     */
    public void setUpdateDate(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>haaim_db.curriculum.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, Integer, Integer, Integer, String, String, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, Integer, Integer, Integer, String, String, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return JCurriculum.CURRICULUM.NO;
    }

    @Override
    public Field<Integer> field2() {
        return JCurriculum.CURRICULUM.YEAR;
    }

    @Override
    public Field<Integer> field3() {
        return JCurriculum.CURRICULUM.GRADE;
    }

    @Override
    public Field<Integer> field4() {
        return JCurriculum.CURRICULUM.COURSE;
    }

    @Override
    public Field<String> field5() {
        return JCurriculum.CURRICULUM.LARGE_CATEGORY;
    }

    @Override
    public Field<String> field6() {
        return JCurriculum.CURRICULUM.MEDIUM_CATEGORY;
    }

    @Override
    public Field<String> field7() {
        return JCurriculum.CURRICULUM.INPUT_ID;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return JCurriculum.CURRICULUM.INPUT_DATE;
    }

    @Override
    public Field<String> field9() {
        return JCurriculum.CURRICULUM.UPDATE_ID;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return JCurriculum.CURRICULUM.UPDATE_DATE;
    }

    @Override
    public Integer component1() {
        return getNo();
    }

    @Override
    public Integer component2() {
        return getYear();
    }

    @Override
    public Integer component3() {
        return getGrade();
    }

    @Override
    public Integer component4() {
        return getCourse();
    }

    @Override
    public String component5() {
        return getLargeCategory();
    }

    @Override
    public String component6() {
        return getMediumCategory();
    }

    @Override
    public String component7() {
        return getInputId();
    }

    @Override
    public LocalDateTime component8() {
        return getInputDate();
    }

    @Override
    public String component9() {
        return getUpdateId();
    }

    @Override
    public LocalDateTime component10() {
        return getUpdateDate();
    }

    @Override
    public Integer value1() {
        return getNo();
    }

    @Override
    public Integer value2() {
        return getYear();
    }

    @Override
    public Integer value3() {
        return getGrade();
    }

    @Override
    public Integer value4() {
        return getCourse();
    }

    @Override
    public String value5() {
        return getLargeCategory();
    }

    @Override
    public String value6() {
        return getMediumCategory();
    }

    @Override
    public String value7() {
        return getInputId();
    }

    @Override
    public LocalDateTime value8() {
        return getInputDate();
    }

    @Override
    public String value9() {
        return getUpdateId();
    }

    @Override
    public LocalDateTime value10() {
        return getUpdateDate();
    }

    @Override
    public JCurriculumRecord value1(Integer value) {
        setNo(value);
        return this;
    }

    @Override
    public JCurriculumRecord value2(Integer value) {
        setYear(value);
        return this;
    }

    @Override
    public JCurriculumRecord value3(Integer value) {
        setGrade(value);
        return this;
    }

    @Override
    public JCurriculumRecord value4(Integer value) {
        setCourse(value);
        return this;
    }

    @Override
    public JCurriculumRecord value5(String value) {
        setLargeCategory(value);
        return this;
    }

    @Override
    public JCurriculumRecord value6(String value) {
        setMediumCategory(value);
        return this;
    }

    @Override
    public JCurriculumRecord value7(String value) {
        setInputId(value);
        return this;
    }

    @Override
    public JCurriculumRecord value8(LocalDateTime value) {
        setInputDate(value);
        return this;
    }

    @Override
    public JCurriculumRecord value9(String value) {
        setUpdateId(value);
        return this;
    }

    @Override
    public JCurriculumRecord value10(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    @Override
    public JCurriculumRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5, String value6, String value7, LocalDateTime value8, String value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JCurriculumRecord
     */
    public JCurriculumRecord() {
        super(JCurriculum.CURRICULUM);
    }

    /**
     * Create a detached, initialised JCurriculumRecord
     */
    public JCurriculumRecord(Integer no, Integer year, Integer grade, Integer course, String largeCategory, String mediumCategory, String inputId, LocalDateTime inputDate, String updateId, LocalDateTime updateDate) {
        super(JCurriculum.CURRICULUM);

        set(0, no);
        set(1, year);
        set(2, grade);
        set(3, course);
        set(4, largeCategory);
        set(5, mediumCategory);
        set(6, inputId);
        set(7, inputDate);
        set(8, updateId);
        set(9, updateDate);
    }
}
