/*
 * This file is generated by jOOQ.
 */
package net.haaim.web.jooq.entity.tables.records;


import java.time.LocalDateTime;

import net.haaim.web.jooq.entity.tables.JExamUser;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 시험대상 목록
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JExamUserRecord extends UpdatableRecordImpl<JExamUserRecord> implements Record9<Integer, Integer, Integer, Integer, String, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = -1166855150;

    /**
     * Setter for <code>haaim_db.exam_user.exam_no</code>. 출제지번호
     */
    public void setExamNo(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>haaim_db.exam_user.exam_no</code>. 출제지번호
     */
    public Integer getExamNo() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>haaim_db.exam_user.student_no</code>. 대상자ID
     */
    public void setStudentNo(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>haaim_db.exam_user.student_no</code>. 대상자ID
     */
    public Integer getStudentNo() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>haaim_db.exam_user.status</code>. 1:미응시, 2:응시, 3:채점
     */
    public void setStatus(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>haaim_db.exam_user.status</code>. 1:미응시, 2:응시, 3:채점
     */
    public Integer getStatus() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>haaim_db.exam_user.score</code>. 시험점수
     */
    public void setScore(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>haaim_db.exam_user.score</code>. 시험점수
     */
    public Integer getScore() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>haaim_db.exam_user.comments</code>. 학생의견
     */
    public void setComments(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>haaim_db.exam_user.comments</code>. 학생의견
     */
    public String getComments() {
        return (String) get(4);
    }

    /**
     * Setter for <code>haaim_db.exam_user.input_id</code>.
     */
    public void setInputId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>haaim_db.exam_user.input_id</code>.
     */
    public String getInputId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>haaim_db.exam_user.input_date</code>.
     */
    public void setInputDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>haaim_db.exam_user.input_date</code>.
     */
    public LocalDateTime getInputDate() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>haaim_db.exam_user.update_id</code>.
     */
    public void setUpdateId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>haaim_db.exam_user.update_id</code>.
     */
    public String getUpdateId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>haaim_db.exam_user.update_date</code>.
     */
    public void setUpdateDate(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>haaim_db.exam_user.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, Integer, Integer, Integer, String, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, Integer, Integer, Integer, String, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return JExamUser.EXAM_USER.EXAM_NO;
    }

    @Override
    public Field<Integer> field2() {
        return JExamUser.EXAM_USER.STUDENT_NO;
    }

    @Override
    public Field<Integer> field3() {
        return JExamUser.EXAM_USER.STATUS;
    }

    @Override
    public Field<Integer> field4() {
        return JExamUser.EXAM_USER.SCORE;
    }

    @Override
    public Field<String> field5() {
        return JExamUser.EXAM_USER.COMMENTS;
    }

    @Override
    public Field<String> field6() {
        return JExamUser.EXAM_USER.INPUT_ID;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return JExamUser.EXAM_USER.INPUT_DATE;
    }

    @Override
    public Field<String> field8() {
        return JExamUser.EXAM_USER.UPDATE_ID;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return JExamUser.EXAM_USER.UPDATE_DATE;
    }

    @Override
    public Integer component1() {
        return getExamNo();
    }

    @Override
    public Integer component2() {
        return getStudentNo();
    }

    @Override
    public Integer component3() {
        return getStatus();
    }

    @Override
    public Integer component4() {
        return getScore();
    }

    @Override
    public String component5() {
        return getComments();
    }

    @Override
    public String component6() {
        return getInputId();
    }

    @Override
    public LocalDateTime component7() {
        return getInputDate();
    }

    @Override
    public String component8() {
        return getUpdateId();
    }

    @Override
    public LocalDateTime component9() {
        return getUpdateDate();
    }

    @Override
    public Integer value1() {
        return getExamNo();
    }

    @Override
    public Integer value2() {
        return getStudentNo();
    }

    @Override
    public Integer value3() {
        return getStatus();
    }

    @Override
    public Integer value4() {
        return getScore();
    }

    @Override
    public String value5() {
        return getComments();
    }

    @Override
    public String value6() {
        return getInputId();
    }

    @Override
    public LocalDateTime value7() {
        return getInputDate();
    }

    @Override
    public String value8() {
        return getUpdateId();
    }

    @Override
    public LocalDateTime value9() {
        return getUpdateDate();
    }

    @Override
    public JExamUserRecord value1(Integer value) {
        setExamNo(value);
        return this;
    }

    @Override
    public JExamUserRecord value2(Integer value) {
        setStudentNo(value);
        return this;
    }

    @Override
    public JExamUserRecord value3(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public JExamUserRecord value4(Integer value) {
        setScore(value);
        return this;
    }

    @Override
    public JExamUserRecord value5(String value) {
        setComments(value);
        return this;
    }

    @Override
    public JExamUserRecord value6(String value) {
        setInputId(value);
        return this;
    }

    @Override
    public JExamUserRecord value7(LocalDateTime value) {
        setInputDate(value);
        return this;
    }

    @Override
    public JExamUserRecord value8(String value) {
        setUpdateId(value);
        return this;
    }

    @Override
    public JExamUserRecord value9(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    @Override
    public JExamUserRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5, String value6, LocalDateTime value7, String value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JExamUserRecord
     */
    public JExamUserRecord() {
        super(JExamUser.EXAM_USER);
    }

    /**
     * Create a detached, initialised JExamUserRecord
     */
    public JExamUserRecord(Integer examNo, Integer studentNo, Integer status, Integer score, String comments, String inputId, LocalDateTime inputDate, String updateId, LocalDateTime updateDate) {
        super(JExamUser.EXAM_USER);

        set(0, examNo);
        set(1, studentNo);
        set(2, status);
        set(3, score);
        set(4, comments);
        set(5, inputId);
        set(6, inputDate);
        set(7, updateId);
        set(8, updateDate);
    }
}
