/*
 * This file is generated by jOOQ.
 */
package net.haaim.web.jooq.entity.tables.records;


import java.time.LocalDateTime;

import net.haaim.web.jooq.entity.tables.JExamItem;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 문제출제
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JExamItemRecord extends UpdatableRecordImpl<JExamItemRecord> implements Record7<Integer, Integer, Integer, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = 1905225288;

    /**
     * Setter for <code>haaim_db.exam_item.exam_no</code>.
     */
    public void setExamNo(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>haaim_db.exam_item.exam_no</code>.
     */
    public Integer getExamNo() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>haaim_db.exam_item.no</code>. 문제순서
     */
    public void setNo(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>haaim_db.exam_item.no</code>. 문제순서
     */
    public Integer getNo() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>haaim_db.exam_item.item_no</code>.
     */
    public void setItemNo(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>haaim_db.exam_item.item_no</code>.
     */
    public Integer getItemNo() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>haaim_db.exam_item.input_id</code>.
     */
    public void setInputId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>haaim_db.exam_item.input_id</code>.
     */
    public String getInputId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>haaim_db.exam_item.input_date</code>.
     */
    public void setInputDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>haaim_db.exam_item.input_date</code>.
     */
    public LocalDateTime getInputDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>haaim_db.exam_item.update_id</code>.
     */
    public void setUpdateId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>haaim_db.exam_item.update_id</code>.
     */
    public String getUpdateId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>haaim_db.exam_item.update_date</code>.
     */
    public void setUpdateDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>haaim_db.exam_item.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<Integer, Integer, Integer> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, Integer, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Integer, Integer, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return JExamItem.EXAM_ITEM.EXAM_NO;
    }

    @Override
    public Field<Integer> field2() {
        return JExamItem.EXAM_ITEM.NO;
    }

    @Override
    public Field<Integer> field3() {
        return JExamItem.EXAM_ITEM.ITEM_NO;
    }

    @Override
    public Field<String> field4() {
        return JExamItem.EXAM_ITEM.INPUT_ID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return JExamItem.EXAM_ITEM.INPUT_DATE;
    }

    @Override
    public Field<String> field6() {
        return JExamItem.EXAM_ITEM.UPDATE_ID;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return JExamItem.EXAM_ITEM.UPDATE_DATE;
    }

    @Override
    public Integer component1() {
        return getExamNo();
    }

    @Override
    public Integer component2() {
        return getNo();
    }

    @Override
    public Integer component3() {
        return getItemNo();
    }

    @Override
    public String component4() {
        return getInputId();
    }

    @Override
    public LocalDateTime component5() {
        return getInputDate();
    }

    @Override
    public String component6() {
        return getUpdateId();
    }

    @Override
    public LocalDateTime component7() {
        return getUpdateDate();
    }

    @Override
    public Integer value1() {
        return getExamNo();
    }

    @Override
    public Integer value2() {
        return getNo();
    }

    @Override
    public Integer value3() {
        return getItemNo();
    }

    @Override
    public String value4() {
        return getInputId();
    }

    @Override
    public LocalDateTime value5() {
        return getInputDate();
    }

    @Override
    public String value6() {
        return getUpdateId();
    }

    @Override
    public LocalDateTime value7() {
        return getUpdateDate();
    }

    @Override
    public JExamItemRecord value1(Integer value) {
        setExamNo(value);
        return this;
    }

    @Override
    public JExamItemRecord value2(Integer value) {
        setNo(value);
        return this;
    }

    @Override
    public JExamItemRecord value3(Integer value) {
        setItemNo(value);
        return this;
    }

    @Override
    public JExamItemRecord value4(String value) {
        setInputId(value);
        return this;
    }

    @Override
    public JExamItemRecord value5(LocalDateTime value) {
        setInputDate(value);
        return this;
    }

    @Override
    public JExamItemRecord value6(String value) {
        setUpdateId(value);
        return this;
    }

    @Override
    public JExamItemRecord value7(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    @Override
    public JExamItemRecord values(Integer value1, Integer value2, Integer value3, String value4, LocalDateTime value5, String value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JExamItemRecord
     */
    public JExamItemRecord() {
        super(JExamItem.EXAM_ITEM);
    }

    /**
     * Create a detached, initialised JExamItemRecord
     */
    public JExamItemRecord(Integer examNo, Integer no, Integer itemNo, String inputId, LocalDateTime inputDate, String updateId, LocalDateTime updateDate) {
        super(JExamItem.EXAM_ITEM);

        set(0, examNo);
        set(1, no);
        set(2, itemNo);
        set(3, inputId);
        set(4, inputDate);
        set(5, updateId);
        set(6, updateDate);
    }
}
