/*
 * This file is generated by jOOQ.
 */
package net.haaim.web.jooq.entity.tables.records;


import java.time.LocalDateTime;

import net.haaim.web.jooq.entity.tables.JGroupCode;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 코드 그룹
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JGroupCodeRecord extends UpdatableRecordImpl<JGroupCodeRecord> implements Record8<Integer, String, String, Integer, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = 675055819;

    /**
     * Setter for <code>haaim_db.group_code.no</code>.
     */
    public void setNo(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>haaim_db.group_code.no</code>.
     */
    public Integer getNo() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>haaim_db.group_code.code</code>. 코드
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>haaim_db.group_code.code</code>. 코드
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>haaim_db.group_code.code_name</code>. 코드명
     */
    public void setCodeName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>haaim_db.group_code.code_name</code>. 코드명
     */
    public String getCodeName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>haaim_db.group_code.use_yn</code>. 사용여부
     */
    public void setUseYn(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>haaim_db.group_code.use_yn</code>. 사용여부
     */
    public Integer getUseYn() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>haaim_db.group_code.input_id</code>.
     */
    public void setInputId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>haaim_db.group_code.input_id</code>.
     */
    public String getInputId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>haaim_db.group_code.input_date</code>.
     */
    public void setInputDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>haaim_db.group_code.input_date</code>.
     */
    public LocalDateTime getInputDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>haaim_db.group_code.update_id</code>.
     */
    public void setUpdateId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>haaim_db.group_code.update_id</code>.
     */
    public String getUpdateId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>haaim_db.group_code.update_date</code>.
     */
    public void setUpdateDate(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>haaim_db.group_code.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, Integer, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, String, Integer, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return JGroupCode.GROUP_CODE.NO;
    }

    @Override
    public Field<String> field2() {
        return JGroupCode.GROUP_CODE.CODE;
    }

    @Override
    public Field<String> field3() {
        return JGroupCode.GROUP_CODE.CODE_NAME;
    }

    @Override
    public Field<Integer> field4() {
        return JGroupCode.GROUP_CODE.USE_YN;
    }

    @Override
    public Field<String> field5() {
        return JGroupCode.GROUP_CODE.INPUT_ID;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return JGroupCode.GROUP_CODE.INPUT_DATE;
    }

    @Override
    public Field<String> field7() {
        return JGroupCode.GROUP_CODE.UPDATE_ID;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return JGroupCode.GROUP_CODE.UPDATE_DATE;
    }

    @Override
    public Integer component1() {
        return getNo();
    }

    @Override
    public String component2() {
        return getCode();
    }

    @Override
    public String component3() {
        return getCodeName();
    }

    @Override
    public Integer component4() {
        return getUseYn();
    }

    @Override
    public String component5() {
        return getInputId();
    }

    @Override
    public LocalDateTime component6() {
        return getInputDate();
    }

    @Override
    public String component7() {
        return getUpdateId();
    }

    @Override
    public LocalDateTime component8() {
        return getUpdateDate();
    }

    @Override
    public Integer value1() {
        return getNo();
    }

    @Override
    public String value2() {
        return getCode();
    }

    @Override
    public String value3() {
        return getCodeName();
    }

    @Override
    public Integer value4() {
        return getUseYn();
    }

    @Override
    public String value5() {
        return getInputId();
    }

    @Override
    public LocalDateTime value6() {
        return getInputDate();
    }

    @Override
    public String value7() {
        return getUpdateId();
    }

    @Override
    public LocalDateTime value8() {
        return getUpdateDate();
    }

    @Override
    public JGroupCodeRecord value1(Integer value) {
        setNo(value);
        return this;
    }

    @Override
    public JGroupCodeRecord value2(String value) {
        setCode(value);
        return this;
    }

    @Override
    public JGroupCodeRecord value3(String value) {
        setCodeName(value);
        return this;
    }

    @Override
    public JGroupCodeRecord value4(Integer value) {
        setUseYn(value);
        return this;
    }

    @Override
    public JGroupCodeRecord value5(String value) {
        setInputId(value);
        return this;
    }

    @Override
    public JGroupCodeRecord value6(LocalDateTime value) {
        setInputDate(value);
        return this;
    }

    @Override
    public JGroupCodeRecord value7(String value) {
        setUpdateId(value);
        return this;
    }

    @Override
    public JGroupCodeRecord value8(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    @Override
    public JGroupCodeRecord values(Integer value1, String value2, String value3, Integer value4, String value5, LocalDateTime value6, String value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JGroupCodeRecord
     */
    public JGroupCodeRecord() {
        super(JGroupCode.GROUP_CODE);
    }

    /**
     * Create a detached, initialised JGroupCodeRecord
     */
    public JGroupCodeRecord(Integer no, String code, String codeName, Integer useYn, String inputId, LocalDateTime inputDate, String updateId, LocalDateTime updateDate) {
        super(JGroupCode.GROUP_CODE);

        set(0, no);
        set(1, code);
        set(2, codeName);
        set(3, useYn);
        set(4, inputId);
        set(5, inputDate);
        set(6, updateId);
        set(7, updateDate);
    }
}
