/*
 * This file is generated by jOOQ.
 */
package net.haaim.web.jooq.entity.tables.records;


import java.time.LocalDateTime;

import net.haaim.web.jooq.entity.tables.JItemPool;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 문제은행
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JItemPoolRecord extends UpdatableRecordImpl<JItemPoolRecord> {

    private static final long serialVersionUID = 1377775867;

    /**
     * Setter for <code>haaim_db.item_pool.item_no</code>.
     */
    public void setItemNo(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>haaim_db.item_pool.item_no</code>.
     */
    public Integer getItemNo() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>haaim_db.item_pool.year</code>.
     */
    public void setYear(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>haaim_db.item_pool.year</code>.
     */
    public Integer getYear() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>haaim_db.item_pool.grade</code>.
     */
    public void setGrade(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>haaim_db.item_pool.grade</code>.
     */
    public Integer getGrade() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>haaim_db.item_pool.course</code>.
     */
    public void setCourse(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>haaim_db.item_pool.course</code>.
     */
    public Integer getCourse() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>haaim_db.item_pool.medium_category</code>. 중분류코드
     */
    public void setMediumCategory(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>haaim_db.item_pool.medium_category</code>. 중분류코드
     */
    public String getMediumCategory() {
        return (String) get(4);
    }

    /**
     * Setter for <code>haaim_db.item_pool.type_group</code>. 유형그룹
     */
    public void setTypeGroup(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>haaim_db.item_pool.type_group</code>. 유형그룹
     */
    public String getTypeGroup() {
        return (String) get(5);
    }

    /**
     * Setter for <code>haaim_db.item_pool.type</code>. 유형
     */
    public void setType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>haaim_db.item_pool.type</code>. 유형
     */
    public String getType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>haaim_db.item_pool.question_type</code>. 문제형태(객관식/주관식)
     */
    public void setQuestionType(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>haaim_db.item_pool.question_type</code>. 문제형태(객관식/주관식)
     */
    public Integer getQuestionType() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>haaim_db.item_pool.question</code>.
     */
    public void setQuestion(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>haaim_db.item_pool.question</code>.
     */
    public String getQuestion() {
        return (String) get(8);
    }

    /**
     * Setter for <code>haaim_db.item_pool.choice1</code>. 객관식 보기1
     */
    public void setChoice1(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>haaim_db.item_pool.choice1</code>. 객관식 보기1
     */
    public String getChoice1() {
        return (String) get(9);
    }

    /**
     * Setter for <code>haaim_db.item_pool.choice2</code>. 객관식 보기2
     */
    public void setChoice2(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>haaim_db.item_pool.choice2</code>. 객관식 보기2
     */
    public String getChoice2() {
        return (String) get(10);
    }

    /**
     * Setter for <code>haaim_db.item_pool.choice3</code>. 객관식 보기3
     */
    public void setChoice3(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>haaim_db.item_pool.choice3</code>. 객관식 보기3
     */
    public String getChoice3() {
        return (String) get(11);
    }

    /**
     * Setter for <code>haaim_db.item_pool.choice4</code>. 객관식 보기4
     */
    public void setChoice4(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>haaim_db.item_pool.choice4</code>. 객관식 보기4
     */
    public String getChoice4() {
        return (String) get(12);
    }

    /**
     * Setter for <code>haaim_db.item_pool.choice5</code>. 객관식 보기5
     */
    public void setChoice5(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>haaim_db.item_pool.choice5</code>. 객관식 보기5
     */
    public String getChoice5() {
        return (String) get(13);
    }

    /**
     * Setter for <code>haaim_db.item_pool.file_path</code>.
     */
    public void setFilePath(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>haaim_db.item_pool.file_path</code>.
     */
    public String getFilePath() {
        return (String) get(14);
    }

    /**
     * Setter for <code>haaim_db.item_pool.mark_type</code>. 채점 방법(자동/수동)
     */
    public void setMarkType(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>haaim_db.item_pool.mark_type</code>. 채점 방법(자동/수동)
     */
    public Integer getMarkType() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>haaim_db.item_pool.answer</code>. 주관식 답
     */
    public void setAnswer(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>haaim_db.item_pool.answer</code>. 주관식 답
     */
    public String getAnswer() {
        return (String) get(16);
    }

    /**
     * Setter for <code>haaim_db.item_pool.answer_path</code>. 주관식 답 image
     */
    public void setAnswerPath(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>haaim_db.item_pool.answer_path</code>. 주관식 답 image
     */
    public String getAnswerPath() {
        return (String) get(17);
    }

    /**
     * Setter for <code>haaim_db.item_pool.publisher</code>. 출판사
     */
    public void setPublisher(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>haaim_db.item_pool.publisher</code>. 출판사
     */
    public String getPublisher() {
        return (String) get(18);
    }

    /**
     * Setter for <code>haaim_db.item_pool.workbook</code>. 문제집
     */
    public void setWorkbook(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>haaim_db.item_pool.workbook</code>. 문제집
     */
    public String getWorkbook() {
        return (String) get(19);
    }

    /**
     * Setter for <code>haaim_db.item_pool.level_difficulty</code>. 난이도
     */
    public void setLevelDifficulty(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>haaim_db.item_pool.level_difficulty</code>. 난이도
     */
    public Integer getLevelDifficulty() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>haaim_db.item_pool.use_yn</code>. 사용여부
     */
    public void setUseYn(Integer value) {
        set(21, value);
    }

    /**
     * Getter for <code>haaim_db.item_pool.use_yn</code>. 사용여부
     */
    public Integer getUseYn() {
        return (Integer) get(21);
    }

    /**
     * Setter for <code>haaim_db.item_pool.input_id</code>.
     */
    public void setInputId(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>haaim_db.item_pool.input_id</code>.
     */
    public String getInputId() {
        return (String) get(22);
    }

    /**
     * Setter for <code>haaim_db.item_pool.input_date</code>.
     */
    public void setInputDate(LocalDateTime value) {
        set(23, value);
    }

    /**
     * Getter for <code>haaim_db.item_pool.input_date</code>.
     */
    public LocalDateTime getInputDate() {
        return (LocalDateTime) get(23);
    }

    /**
     * Setter for <code>haaim_db.item_pool.update_id</code>.
     */
    public void setUpdateId(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>haaim_db.item_pool.update_id</code>.
     */
    public String getUpdateId() {
        return (String) get(24);
    }

    /**
     * Setter for <code>haaim_db.item_pool.update_date</code>.
     */
    public void setUpdateDate(LocalDateTime value) {
        set(25, value);
    }

    /**
     * Getter for <code>haaim_db.item_pool.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(25);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JItemPoolRecord
     */
    public JItemPoolRecord() {
        super(JItemPool.ITEM_POOL);
    }

    /**
     * Create a detached, initialised JItemPoolRecord
     */
    public JItemPoolRecord(Integer itemNo, Integer year, Integer grade, Integer course, String mediumCategory, String typeGroup, String type, Integer questionType, String question, String choice1, String choice2, String choice3, String choice4, String choice5, String filePath, Integer markType, String answer, String answerPath, String publisher, String workbook, Integer levelDifficulty, Integer useYn, String inputId, LocalDateTime inputDate, String updateId, LocalDateTime updateDate) {
        super(JItemPool.ITEM_POOL);

        set(0, itemNo);
        set(1, year);
        set(2, grade);
        set(3, course);
        set(4, mediumCategory);
        set(5, typeGroup);
        set(6, type);
        set(7, questionType);
        set(8, question);
        set(9, choice1);
        set(10, choice2);
        set(11, choice3);
        set(12, choice4);
        set(13, choice5);
        set(14, filePath);
        set(15, markType);
        set(16, answer);
        set(17, answerPath);
        set(18, publisher);
        set(19, workbook);
        set(20, levelDifficulty);
        set(21, useYn);
        set(22, inputId);
        set(23, inputDate);
        set(24, updateId);
        set(25, updateDate);
    }
}
