/*
 * This file is generated by jOOQ.
 */
package net.haaim.web.jooq.entity.tables.records;


import java.time.LocalDateTime;

import net.haaim.web.jooq.entity.tables.JMonthlyReport;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 월간리포트
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JMonthlyReportRecord extends UpdatableRecordImpl<JMonthlyReportRecord> implements Record17<Integer, Integer, Integer, Integer, Integer, String, String, String, Integer, Integer, String, String, String, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = -295758513;

    /**
     * Setter for <code>haaim_db.monthly_report.no</code>.
     */
    public void setNo(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>haaim_db.monthly_report.no</code>.
     */
    public Integer getNo() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>haaim_db.monthly_report.class_no</code>.
     */
    public void setClassNo(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>haaim_db.monthly_report.class_no</code>.
     */
    public Integer getClassNo() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>haaim_db.monthly_report.student_no</code>.
     */
    public void setStudentNo(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>haaim_db.monthly_report.student_no</code>.
     */
    public Integer getStudentNo() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>haaim_db.monthly_report.year</code>. 년
     */
    public void setYear(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>haaim_db.monthly_report.year</code>. 년
     */
    public Integer getYear() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>haaim_db.monthly_report.month</code>. 월
     */
    public void setMonth(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>haaim_db.monthly_report.month</code>. 월
     */
    public Integer getMonth() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>haaim_db.monthly_report.title</code>. 월간리포트 타이틀
     */
    public void setTitle(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>haaim_db.monthly_report.title</code>. 월간리포트 타이틀
     */
    public String getTitle() {
        return (String) get(5);
    }

    /**
     * Setter for <code>haaim_db.monthly_report.start_date</code>. 기간 시작일
     */
    public void setStartDate(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>haaim_db.monthly_report.start_date</code>. 기간 시작일
     */
    public String getStartDate() {
        return (String) get(6);
    }

    /**
     * Setter for <code>haaim_db.monthly_report.end_date</code>. 기간 종료일
     */
    public void setEndDate(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>haaim_db.monthly_report.end_date</code>. 기간 종료일
     */
    public String getEndDate() {
        return (String) get(7);
    }

    /**
     * Setter for <code>haaim_db.monthly_report.homework</code>. 과제이행 회수
     */
    public void setHomework(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>haaim_db.monthly_report.homework</code>. 과제이행 회수
     */
    public Integer getHomework() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>haaim_db.monthly_report.homework_total</code>. 과제 총 횟수
     */
    public void setHomeworkTotal(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>haaim_db.monthly_report.homework_total</code>. 과제 총 횟수
     */
    public Integer getHomeworkTotal() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>haaim_db.monthly_report.excellence</code>. 장점
     */
    public void setExcellence(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>haaim_db.monthly_report.excellence</code>. 장점
     */
    public String getExcellence() {
        return (String) get(10);
    }

    /**
     * Setter for <code>haaim_db.monthly_report.goal</code>. 목표
     */
    public void setGoal(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>haaim_db.monthly_report.goal</code>. 목표
     */
    public String getGoal() {
        return (String) get(11);
    }

    /**
     * Setter for <code>haaim_db.monthly_report.notice</code>. 전달사항
     */
    public void setNotice(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>haaim_db.monthly_report.notice</code>. 전달사항
     */
    public String getNotice() {
        return (String) get(12);
    }

    /**
     * Setter for <code>haaim_db.monthly_report.input_id</code>.
     */
    public void setInputId(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>haaim_db.monthly_report.input_id</code>.
     */
    public String getInputId() {
        return (String) get(13);
    }

    /**
     * Setter for <code>haaim_db.monthly_report.input_date</code>.
     */
    public void setInputDate(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>haaim_db.monthly_report.input_date</code>.
     */
    public LocalDateTime getInputDate() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>haaim_db.monthly_report.update_id</code>.
     */
    public void setUpdateId(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>haaim_db.monthly_report.update_id</code>.
     */
    public String getUpdateId() {
        return (String) get(15);
    }

    /**
     * Setter for <code>haaim_db.monthly_report.update_date</code>.
     */
    public void setUpdateDate(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>haaim_db.monthly_report.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row17<Integer, Integer, Integer, Integer, Integer, String, String, String, Integer, Integer, String, String, String, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    @Override
    public Row17<Integer, Integer, Integer, Integer, Integer, String, String, String, Integer, Integer, String, String, String, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row17) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return JMonthlyReport.MONTHLY_REPORT.NO;
    }

    @Override
    public Field<Integer> field2() {
        return JMonthlyReport.MONTHLY_REPORT.CLASS_NO;
    }

    @Override
    public Field<Integer> field3() {
        return JMonthlyReport.MONTHLY_REPORT.STUDENT_NO;
    }

    @Override
    public Field<Integer> field4() {
        return JMonthlyReport.MONTHLY_REPORT.YEAR;
    }

    @Override
    public Field<Integer> field5() {
        return JMonthlyReport.MONTHLY_REPORT.MONTH;
    }

    @Override
    public Field<String> field6() {
        return JMonthlyReport.MONTHLY_REPORT.TITLE;
    }

    @Override
    public Field<String> field7() {
        return JMonthlyReport.MONTHLY_REPORT.START_DATE;
    }

    @Override
    public Field<String> field8() {
        return JMonthlyReport.MONTHLY_REPORT.END_DATE;
    }

    @Override
    public Field<Integer> field9() {
        return JMonthlyReport.MONTHLY_REPORT.HOMEWORK;
    }

    @Override
    public Field<Integer> field10() {
        return JMonthlyReport.MONTHLY_REPORT.HOMEWORK_TOTAL;
    }

    @Override
    public Field<String> field11() {
        return JMonthlyReport.MONTHLY_REPORT.EXCELLENCE;
    }

    @Override
    public Field<String> field12() {
        return JMonthlyReport.MONTHLY_REPORT.GOAL;
    }

    @Override
    public Field<String> field13() {
        return JMonthlyReport.MONTHLY_REPORT.NOTICE;
    }

    @Override
    public Field<String> field14() {
        return JMonthlyReport.MONTHLY_REPORT.INPUT_ID;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return JMonthlyReport.MONTHLY_REPORT.INPUT_DATE;
    }

    @Override
    public Field<String> field16() {
        return JMonthlyReport.MONTHLY_REPORT.UPDATE_ID;
    }

    @Override
    public Field<LocalDateTime> field17() {
        return JMonthlyReport.MONTHLY_REPORT.UPDATE_DATE;
    }

    @Override
    public Integer component1() {
        return getNo();
    }

    @Override
    public Integer component2() {
        return getClassNo();
    }

    @Override
    public Integer component3() {
        return getStudentNo();
    }

    @Override
    public Integer component4() {
        return getYear();
    }

    @Override
    public Integer component5() {
        return getMonth();
    }

    @Override
    public String component6() {
        return getTitle();
    }

    @Override
    public String component7() {
        return getStartDate();
    }

    @Override
    public String component8() {
        return getEndDate();
    }

    @Override
    public Integer component9() {
        return getHomework();
    }

    @Override
    public Integer component10() {
        return getHomeworkTotal();
    }

    @Override
    public String component11() {
        return getExcellence();
    }

    @Override
    public String component12() {
        return getGoal();
    }

    @Override
    public String component13() {
        return getNotice();
    }

    @Override
    public String component14() {
        return getInputId();
    }

    @Override
    public LocalDateTime component15() {
        return getInputDate();
    }

    @Override
    public String component16() {
        return getUpdateId();
    }

    @Override
    public LocalDateTime component17() {
        return getUpdateDate();
    }

    @Override
    public Integer value1() {
        return getNo();
    }

    @Override
    public Integer value2() {
        return getClassNo();
    }

    @Override
    public Integer value3() {
        return getStudentNo();
    }

    @Override
    public Integer value4() {
        return getYear();
    }

    @Override
    public Integer value5() {
        return getMonth();
    }

    @Override
    public String value6() {
        return getTitle();
    }

    @Override
    public String value7() {
        return getStartDate();
    }

    @Override
    public String value8() {
        return getEndDate();
    }

    @Override
    public Integer value9() {
        return getHomework();
    }

    @Override
    public Integer value10() {
        return getHomeworkTotal();
    }

    @Override
    public String value11() {
        return getExcellence();
    }

    @Override
    public String value12() {
        return getGoal();
    }

    @Override
    public String value13() {
        return getNotice();
    }

    @Override
    public String value14() {
        return getInputId();
    }

    @Override
    public LocalDateTime value15() {
        return getInputDate();
    }

    @Override
    public String value16() {
        return getUpdateId();
    }

    @Override
    public LocalDateTime value17() {
        return getUpdateDate();
    }

    @Override
    public JMonthlyReportRecord value1(Integer value) {
        setNo(value);
        return this;
    }

    @Override
    public JMonthlyReportRecord value2(Integer value) {
        setClassNo(value);
        return this;
    }

    @Override
    public JMonthlyReportRecord value3(Integer value) {
        setStudentNo(value);
        return this;
    }

    @Override
    public JMonthlyReportRecord value4(Integer value) {
        setYear(value);
        return this;
    }

    @Override
    public JMonthlyReportRecord value5(Integer value) {
        setMonth(value);
        return this;
    }

    @Override
    public JMonthlyReportRecord value6(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public JMonthlyReportRecord value7(String value) {
        setStartDate(value);
        return this;
    }

    @Override
    public JMonthlyReportRecord value8(String value) {
        setEndDate(value);
        return this;
    }

    @Override
    public JMonthlyReportRecord value9(Integer value) {
        setHomework(value);
        return this;
    }

    @Override
    public JMonthlyReportRecord value10(Integer value) {
        setHomeworkTotal(value);
        return this;
    }

    @Override
    public JMonthlyReportRecord value11(String value) {
        setExcellence(value);
        return this;
    }

    @Override
    public JMonthlyReportRecord value12(String value) {
        setGoal(value);
        return this;
    }

    @Override
    public JMonthlyReportRecord value13(String value) {
        setNotice(value);
        return this;
    }

    @Override
    public JMonthlyReportRecord value14(String value) {
        setInputId(value);
        return this;
    }

    @Override
    public JMonthlyReportRecord value15(LocalDateTime value) {
        setInputDate(value);
        return this;
    }

    @Override
    public JMonthlyReportRecord value16(String value) {
        setUpdateId(value);
        return this;
    }

    @Override
    public JMonthlyReportRecord value17(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    @Override
    public JMonthlyReportRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, String value6, String value7, String value8, Integer value9, Integer value10, String value11, String value12, String value13, String value14, LocalDateTime value15, String value16, LocalDateTime value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JMonthlyReportRecord
     */
    public JMonthlyReportRecord() {
        super(JMonthlyReport.MONTHLY_REPORT);
    }

    /**
     * Create a detached, initialised JMonthlyReportRecord
     */
    public JMonthlyReportRecord(Integer no, Integer classNo, Integer studentNo, Integer year, Integer month, String title, String startDate, String endDate, Integer homework, Integer homeworkTotal, String excellence, String goal, String notice, String inputId, LocalDateTime inputDate, String updateId, LocalDateTime updateDate) {
        super(JMonthlyReport.MONTHLY_REPORT);

        set(0, no);
        set(1, classNo);
        set(2, studentNo);
        set(3, year);
        set(4, month);
        set(5, title);
        set(6, startDate);
        set(7, endDate);
        set(8, homework);
        set(9, homeworkTotal);
        set(10, excellence);
        set(11, goal);
        set(12, notice);
        set(13, inputId);
        set(14, inputDate);
        set(15, updateId);
        set(16, updateDate);
    }
}
