/*
 * This file is generated by jOOQ.
 */
package net.haaim.web.jooq.entity.tables.records;


import java.time.LocalDateTime;

import net.haaim.web.jooq.entity.tables.JUser;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 사용자
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JUserRecord extends UpdatableRecordImpl<JUserRecord> implements Record14<Integer, String, String, Integer, Integer, String, String, String, Integer, Integer, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = 890725165;

    /**
     * Setter for <code>haaim_db.user.no</code>.
     */
    public void setNo(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>haaim_db.user.no</code>.
     */
    public Integer getNo() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>haaim_db.user.user_id</code>.
     */
    public void setUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>haaim_db.user.user_id</code>.
     */
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>haaim_db.user.user_pw</code>.
     */
    public void setUserPw(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>haaim_db.user.user_pw</code>.
     */
    public String getUserPw() {
        return (String) get(2);
    }

    /**
     * Setter for <code>haaim_db.user.user_type</code>. 사용자의구분/권한 ( 4:관리자/3:원장/2:교사/1:코디/0:학생)
     */
    public void setUserType(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>haaim_db.user.user_type</code>. 사용자의구분/권한 ( 4:관리자/3:원장/2:교사/1:코디/0:학생)
     */
    public Integer getUserType() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>haaim_db.user.use_yn</code>. 사용여부
     */
    public void setUseYn(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>haaim_db.user.use_yn</code>. 사용여부
     */
    public Integer getUseYn() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>haaim_db.user.name</code>.
     */
    public void setName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>haaim_db.user.name</code>.
     */
    public String getName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>haaim_db.user.mobile</code>.
     */
    public void setMobile(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>haaim_db.user.mobile</code>.
     */
    public String getMobile() {
        return (String) get(6);
    }

    /**
     * Setter for <code>haaim_db.user.email</code>.
     */
    public void setEmail(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>haaim_db.user.email</code>.
     */
    public String getEmail() {
        return (String) get(7);
    }

    /**
     * Setter for <code>haaim_db.user.student_no</code>.
     */
    public void setStudentNo(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>haaim_db.user.student_no</code>.
     */
    public Integer getStudentNo() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>haaim_db.user.state</code>.
     */
    public void setState(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>haaim_db.user.state</code>.
     */
    public Integer getState() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>haaim_db.user.input_id</code>.
     */
    public void setInputId(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>haaim_db.user.input_id</code>.
     */
    public String getInputId() {
        return (String) get(10);
    }

    /**
     * Setter for <code>haaim_db.user.input_date</code>.
     */
    public void setInputDate(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>haaim_db.user.input_date</code>.
     */
    public LocalDateTime getInputDate() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>haaim_db.user.update_id</code>.
     */
    public void setUpdateId(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>haaim_db.user.update_id</code>.
     */
    public String getUpdateId() {
        return (String) get(12);
    }

    /**
     * Setter for <code>haaim_db.user.update_date</code>.
     */
    public void setUpdateDate(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>haaim_db.user.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Integer, String, String, Integer, Integer, String, String, String, Integer, Integer, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Integer, String, String, Integer, Integer, String, String, String, Integer, Integer, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return JUser.USER.NO;
    }

    @Override
    public Field<String> field2() {
        return JUser.USER.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return JUser.USER.USER_PW;
    }

    @Override
    public Field<Integer> field4() {
        return JUser.USER.USER_TYPE;
    }

    @Override
    public Field<Integer> field5() {
        return JUser.USER.USE_YN;
    }

    @Override
    public Field<String> field6() {
        return JUser.USER.NAME;
    }

    @Override
    public Field<String> field7() {
        return JUser.USER.MOBILE;
    }

    @Override
    public Field<String> field8() {
        return JUser.USER.EMAIL;
    }

    @Override
    public Field<Integer> field9() {
        return JUser.USER.STUDENT_NO;
    }

    @Override
    public Field<Integer> field10() {
        return JUser.USER.STATE;
    }

    @Override
    public Field<String> field11() {
        return JUser.USER.INPUT_ID;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return JUser.USER.INPUT_DATE;
    }

    @Override
    public Field<String> field13() {
        return JUser.USER.UPDATE_ID;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return JUser.USER.UPDATE_DATE;
    }

    @Override
    public Integer component1() {
        return getNo();
    }

    @Override
    public String component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getUserPw();
    }

    @Override
    public Integer component4() {
        return getUserType();
    }

    @Override
    public Integer component5() {
        return getUseYn();
    }

    @Override
    public String component6() {
        return getName();
    }

    @Override
    public String component7() {
        return getMobile();
    }

    @Override
    public String component8() {
        return getEmail();
    }

    @Override
    public Integer component9() {
        return getStudentNo();
    }

    @Override
    public Integer component10() {
        return getState();
    }

    @Override
    public String component11() {
        return getInputId();
    }

    @Override
    public LocalDateTime component12() {
        return getInputDate();
    }

    @Override
    public String component13() {
        return getUpdateId();
    }

    @Override
    public LocalDateTime component14() {
        return getUpdateDate();
    }

    @Override
    public Integer value1() {
        return getNo();
    }

    @Override
    public String value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getUserPw();
    }

    @Override
    public Integer value4() {
        return getUserType();
    }

    @Override
    public Integer value5() {
        return getUseYn();
    }

    @Override
    public String value6() {
        return getName();
    }

    @Override
    public String value7() {
        return getMobile();
    }

    @Override
    public String value8() {
        return getEmail();
    }

    @Override
    public Integer value9() {
        return getStudentNo();
    }

    @Override
    public Integer value10() {
        return getState();
    }

    @Override
    public String value11() {
        return getInputId();
    }

    @Override
    public LocalDateTime value12() {
        return getInputDate();
    }

    @Override
    public String value13() {
        return getUpdateId();
    }

    @Override
    public LocalDateTime value14() {
        return getUpdateDate();
    }

    @Override
    public JUserRecord value1(Integer value) {
        setNo(value);
        return this;
    }

    @Override
    public JUserRecord value2(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public JUserRecord value3(String value) {
        setUserPw(value);
        return this;
    }

    @Override
    public JUserRecord value4(Integer value) {
        setUserType(value);
        return this;
    }

    @Override
    public JUserRecord value5(Integer value) {
        setUseYn(value);
        return this;
    }

    @Override
    public JUserRecord value6(String value) {
        setName(value);
        return this;
    }

    @Override
    public JUserRecord value7(String value) {
        setMobile(value);
        return this;
    }

    @Override
    public JUserRecord value8(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public JUserRecord value9(Integer value) {
        setStudentNo(value);
        return this;
    }

    @Override
    public JUserRecord value10(Integer value) {
        setState(value);
        return this;
    }

    @Override
    public JUserRecord value11(String value) {
        setInputId(value);
        return this;
    }

    @Override
    public JUserRecord value12(LocalDateTime value) {
        setInputDate(value);
        return this;
    }

    @Override
    public JUserRecord value13(String value) {
        setUpdateId(value);
        return this;
    }

    @Override
    public JUserRecord value14(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    @Override
    public JUserRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5, String value6, String value7, String value8, Integer value9, Integer value10, String value11, LocalDateTime value12, String value13, LocalDateTime value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JUserRecord
     */
    public JUserRecord() {
        super(JUser.USER);
    }

    /**
     * Create a detached, initialised JUserRecord
     */
    public JUserRecord(Integer no, String userId, String userPw, Integer userType, Integer useYn, String name, String mobile, String email, Integer studentNo, Integer state, String inputId, LocalDateTime inputDate, String updateId, LocalDateTime updateDate) {
        super(JUser.USER);

        set(0, no);
        set(1, userId);
        set(2, userPw);
        set(3, userType);
        set(4, useYn);
        set(5, name);
        set(6, mobile);
        set(7, email);
        set(8, studentNo);
        set(9, state);
        set(10, inputId);
        set(11, inputDate);
        set(12, updateId);
        set(13, updateDate);
    }
}
