
---
spring:
    profiles: local
    
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/haaim_db?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&charaterEncoding=utf-8&serverTimezone=UTC
        username: haaim
        password: haaim01
    output:
        ansi:
            enabled: always
           
    jpa:
        hibernate.ddl-auto: validate
        generate-ddl: true
        show-sql: true
    jwt:
        secret: http://www.jdi.net/mathematics_educational_institution
        expiration: 3600000
        
logging:
    pattern:
        console: "%d %-5level %logger : %msg%n"
    level:
        org.springframework.web: DEBUG
        org.hibernate: DEBUG
        net: DEBUG
            
---
spring:
    profiles: prod
    
    datasource:
        jndi-name: jndi/jtheways
    jpa:
        hibernate.ddl-auto: none
        show-sql: true