openapi: 3.0.0
info:
  title: title
  description: code.
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: haaim

paths:
  /code/list:
    get:
      summary: code 목록 조회.
      security:
        - BasicAuth: []
      parameters:
        - in: query
          name: page_no
          schema:
            type: integer
            required: false
            default: 1
          description: 페이지 번호.
        - in: query
          name: page_size
          schema:
            type: integer
            required: false
            default: 1
          description: 페이지 당 표시 개수.
        - in: query
          name: use_yn
          schema:
            type: integer
            required: false
          description: 사용여부.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                typs: object
                items:
                  $ref: '#/components/schemas/CodeEntity'
         
  /code/save:
    get:
      summary: code 저장.
      security:
        - BasicAuth: []
      parameters:
        - $ref: '#/components/schemas/CodeEntity'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                typs: object
                items:
                  $ref: '#/components/schemas/CodeEntity'
  /code/group/list:
    get:
      summary: code group 목록 조회.
      security:
        - BasicAuth: []
      parameters:
        - in: query
          name: page_no
          schema:
            type: integer
            required: false
            default: 1
          description: 페이지 번호.
        - in: query
          name: page_size
          schema:
            type: integer
            required: false
            default: 1
          description: 페이지 당 표시 개수.
        - in: query
          name: use_yn
          schema:
            type: integer
            required: false
          description: 사용 여부.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                typs: object
                items:
                  $ref: '#/components/schemas/CodeGroupEntity'
  /code/group/save:
    get:
      summary: code group 저장.
      security:
        - BasicAuth: []
      parameters:
        - $ref: '#/components/schemas/CodeGroupEntity'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                typs: object
                items:
                  $ref: '#/components/schemas/CodeGroupEntity'              
components:
  schemas:
    CodeEntity:
      type: object
      properties:
        groupCode:
          type: string
        code:
          type: string
        codeName:
          type: string
        useYn:
          type: integer
        input_id:
          type: string
        input_date:
          type: object
        update_id:
          type: string
        update_date:
          type: object
        
    CodeGroupEntity:
      type: object
      properties:
        code:
          type: string
        codeName:
          type: string
        useYn:
          type: integer
        input_id:
          type: string
        input_date:
          type: object
        update_id:
          type: string
        update_date:
          type: object
    
        
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
      in: header
      
      