openapi: 3.0.0
info:
  title: title
  description: description
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: ddldlddl

paths:
  /student/monthly/attendance/status/{student_no}:
    get:
      summary: 학생의 월별 출석 현황.
      security:
        - BasicAuth: []
      parameters:
        - $ref: '#/components/parameters/studentNoParam'
        - in: query
          name: year
          schema:
            type: integer
          required: false
          description: 기준 년도
        - in: query
          name: month
          schema:
            type: integer
          required: false
          description: 기준 월
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                typs: object
                items:
                  $ref: '#/components/schemas/MonthlyAttendanceStatusEntity'
  /system/menu/all:
    get:
      summary: 메뉴 전체 목록 조회.
      security:
        - BasicAuth: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                typs: object
                items:
                  $ref: '#/components/schemas/MenuEntity'
 

components:
  schemas:
    MonthlyAttendanceStatusEntity:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    MenuEntity:
      type: object
      properties:
        menuCode:
          type: string
        menuName:
          type: string
        parentMenuCode:
          type: string
        depth:
          type: integer
        url:
          type: string
        useYn:
          type: integer
        sort:
          type: integer
          
  parameters:
    studentNoParam:
      name: student_no
      in: path
      description: description
      schema:
        type: interger
        format: int32
        requered: true
        
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
      in: header
      
      